##
## Use as much as we can from the Salsa CI team jobs.
##
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/pipeline-jobs.yml

##
## We don't build any package targetting "all", so the regular build
## rules provide sufficient coverage.
##
variables:
  SALSA_CI_DISABLE_BUILD_PACKAGE_ALL: '1'
  SALSA_CI_DISABLE_BUILD_PACKAGE_ANY: '1'
